// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4IXXG-AP1ITKeInr0mI579AjecSsRYB0',
    appId: '1:721066039365:web:90bfa5c2689a9a332a6b2c',
    messagingSenderId: '721066039365',
    projectId: 'my-cool-app-car',
    authDomain: 'my-cool-app-car.firebaseapp.com',
    storageBucket: 'my-cool-app-car.appspot.com',
    measurementId: 'G-WQ3TEFLWQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWQod9FkLuaxcNGgnWuKVbAGzVMilOXpM',
    appId: '1:721066039365:android:9db13c1312c59e202a6b2c',
    messagingSenderId: '721066039365',
    projectId: 'my-cool-app-car',
    storageBucket: 'my-cool-app-car.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFppf7o_HtYiqCj4D6UF_jyiCrOzefctQ',
    appId: '1:721066039365:ios:b45a15abb9609b202a6b2c',
    messagingSenderId: '721066039365',
    projectId: 'my-cool-app-car',
    storageBucket: 'my-cool-app-car.appspot.com',
    iosClientId: '721066039365-vhmtuarmk1ike2lsmv7jbk7pkg4lh3dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCar',
  );
}
